# Generated by Django 5.2.7 on 2025-11-20 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_announcement_feecategory_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error', models.TextField(blank=True, null=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.announcement')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.parent')),
            ],
            options={
                'unique_together': {('announcement', 'parent')},
            },
        ),
    ]
