# Generated by Django 5.2.7 on 2025-11-24 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_announcementstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='feecategory',
            name='term',
            field=models.CharField(blank=True, choices=[('Term 1', 'Term 1'), ('Term 2', 'Term 2'), ('Term 3', 'Term 3')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='feecategory',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
