"""
Django settings for Dan project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import pymysql
pymysql.install_as_MySQLdb()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-jlis$@ra#k!^wd4ay@h0zvln8ry#kch%ev#+@6eo#&c)(74np^'
AUTHENTICATION_BACKENDS = [
    'store.backends.AdmissionNoBackend',
    'django.contrib.auth.backends.ModelBackend',
]
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost','127.0.0.1','danstudentsystem.onrender.com']


# Application definition
AUTH_USER_MODEL = 'store.Student'

INSTALLED_APPS = [
    "jazzmin",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'store.apps.StoreConfig',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', 
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Dan.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Dan.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
import os

USE_REMOTE_DB = True  # Change to False for local development

if USE_REMOTE_DB:
    DATABASES={
         'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'bneksatanfxwmejf0qr8',  # Your Clever Cloud DB name
            'USER': 'uyw4qg2g2c9gxzkp',
            'PASSWORD': '8aWYEMnzkoUFpQc1HNwL',
            'HOST': 'bneksatanfxwmejf0qr8-mysql.services.clever-cloud.com',
            'PORT': '3306',
            'OPTIONS': {
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            },
        }
    }
else:
 DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME':'school',
        'USER': 'root',
        'PASSWORD':'Manchester45??',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}

X_FRAME_OPTIONS = 'SAMEORIGIN'

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
AFRICASTALKING_USERNAME = "sandbox"
AFRICASTALKING_API_KEY = "atsk_9d6c5f7f614eba63f0d9621a1a3b02f1a83460c12f37d23f58b2f7797081a2ee7a3cd5d0"



# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

STATICFILES_DIRS = [
    BASE_DIR / "store" / "static",  # if your static folder is inside the store app
]
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
 # if you have a 'static' folder in your project
STATIC_ROOT = BASE_DIR / 'staticfiles'     # where collected files will go

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
import os
if not DEBUG:  # Render production mode
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
